<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-14T01:19:30 IST" name="Default suite" finished-at="2023-12-14T01:19:37 IST" duration-ms="6709">
    <groups>
      <group name="smoke">
        <method signature="CreateJobApiRequest.test_if_data_entered_correctly_in_DB()[pri:0, instance:com.api.tests.CreateJobApiRequest@5ba3f27a]" name="test_if_data_entered_correctly_in_DB" class="com.api.tests.CreateJobApiRequest"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="CreateJobApiRequest.test_if_data_entered_correctly_in_DB()[pri:0, instance:com.api.tests.CreateJobApiRequest@5ba3f27a]" name="test_if_data_entered_correctly_in_DB" class="com.api.tests.CreateJobApiRequest"/>
      </group> <!-- sanity -->
      <group name="e2e">
        <method signature="CreateJobApiRequest.test_if_data_entered_correctly_in_DB()[pri:0, instance:com.api.tests.CreateJobApiRequest@5ba3f27a]" name="test_if_data_entered_correctly_in_DB" class="com.api.tests.CreateJobApiRequest"/>
      </group> <!-- e2e -->
    </groups>
    <test started-at="2023-12-14T01:19:30 IST" name="Default test" finished-at="2023-12-14T01:19:37 IST" duration-ms="6709">
      <class name="com.api.tests.CreateJobApiRequest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.api.tests.CreateJobApiRequest@5ba3f27a]" started-at="2023-12-14T01:19:30 IST" name="setup" description="setting up the base URL for the API using config file" finished-at="2023-12-14T01:19:31 IST" duration-ms="788" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Test_api_create_joB()[pri:0, instance:com.api.tests.CreateJobApiRequest@5ba3f27a]" started-at="2023-12-14T01:19:31 IST" name="Test_api_create_joB" finished-at="2023-12-14T01:19:37 IST" duration-ms="5753" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.lang.Long.longValue()" because the return value of "io.restassured.internal.common.path.ObjectConverter.convertObjectTo(Object, java.lang.Class)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "io.restassured.internal.common.path.ObjectConverter.convertObjectTo(Object, java.lang.Class)" is null
at io.restassured.path.json.JsonPath.getLong(JsonPath.java:340)
at com.api.tests.CreateJobApiRequest.Test_api_create_joB(CreateJobApiRequest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_api_create_joB -->
        <test-method signature="test_if_data_entered_correctly_in_DB()[pri:0, instance:com.api.tests.CreateJobApiRequest@5ba3f27a]" started-at="2023-12-14T01:19:37 IST" name="test_if_data_entered_correctly_in_DB" description="Verify customer data entered correctly in db" finished-at="2023-12-14T01:19:37 IST" depends-on-methods="Test_api_create_joB()" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.api.tests.CreateJobApiRequest.test_if_data_entered_correctly_in_DB() on instance com.api.tests.CreateJobApiRequest@5ba3f27a depends on not successfully finished methods 
[com.api.tests.CreateJobApiRequest.Test_api_create_joB() on instance com.api.tests.CreateJobApiRequest@5ba3f27a]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.api.tests.CreateJobApiRequest.test_if_data_entered_correctly_in_DB() on instance com.api.tests.CreateJobApiRequest@5ba3f27a depends on not successfully finished methods 
[com.api.tests.CreateJobApiRequest.Test_api_create_joB() on instance com.api.tests.CreateJobApiRequest@5ba3f27a]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_if_data_entered_correctly_in_DB -->
      </class> <!-- com.api.tests.CreateJobApiRequest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
